# Generated by Django 3.0.4 on 2020-03-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=255)),
                ('data_int', models.IntegerField(null=True)),
            ],
        ),
    ]
