# Generated by Django 3.0.4 on 2020-03-25 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancy_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slot_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 23, 19, 11, 204904)),
        ),
    ]
