# Generated by Django 3.0.4 on 2020-03-21 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distancy_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='data_int',
        ),
    ]
