# Generated by Django 3.0.4 on 2020-03-26 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancy_server', '0002_reservation_slot_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slot_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 20, 14, 14, 764033)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slot_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 20, 14, 14, 764033)),
        ),
    ]
