# Generated by Django 3.0.4 on 2020-03-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancy_server', '0003_auto_20200325_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slot_time_end',
            field=models.DateTimeField(),
        ),
    ]
