# Generated by Django 3.0.4 on 2020-03-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distancy_server', '0004_auto_20200325_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slot_time_end',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='state',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='store',
            name='street_address',
            field=models.CharField(db_index=True, max_length=511),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
